docs_dir: doc/book/ru
pages:
    - index.md
site_name: zf-form
site_description: 'Модуль для унификации работы с формами ZF'
repo_url: 'https://github.com/old-town/workflow-admin'
copyright: 'Copyright (c) 2016 <a href="https://github.com/nnx-framework">NNX</a>'
